# Node.js'in resmi imajını kullanıyoruz
FROM node:18

# Çalışma dizinini oluştur ve ayarla
WORKDIR /app

# package.json ve package-lock.json dosyalarını kopyala
COPY package*.json ./

# Bağımlılıkları yükle
RUN npm install

# Uygulama kodunu kopyala
COPY . .

# API'nin çalışacağı portu belirle
EXPOSE 3000

# API'yi başlat
CMD ["npm", "start"]
